/** Central query-key registry so mutations can invalidate precisely. */
export const qk = {
  me: ["app", "me"] as const,
  profile: ["app", "profile"] as const,
  cars: ["app", "cars"] as const,
  car: (id: string) => ["app", "cars", id] as const,
  tripSearch: (params: unknown) => ["app", "trips", "search", params] as const,
  trip: (id: string) => ["app", "trips", id] as const,
  tripBookings: (id: string, status?: string) => ["app", "trips", id, "bookings", status ?? "all"] as const,
  myActivity: (role: string) => ["app", "trips", "activity", role] as const,
  priceHint: (from: string, to: string) => ["app", "trips", "price-hint", from, to] as const,
  booking: (id: string) => ["app", "bookings", id] as const,
  parcels: ["app", "parcels"] as const,
  parcel: (id: string) => ["app", "parcels", id] as const,
  tripParcels: (id: string) => ["app", "trips", id, "parcels"] as const,
  wallet: ["app", "wallet"] as const,
  transactions: ["app", "wallet", "transactions"] as const,
  cards: ["app", "cards"] as const,
  chats: ["app", "chats"] as const,
  chatMessages: (id: string) => ["app", "chats", id, "messages"] as const,
  notifications: ["app", "notifications"] as const,
  ratings: (userId: string) => ["app", "ratings", userId] as const,
  promocodes: ["app", "promocodes"] as const,
  referral: ["app", "referral"] as const,
  blockedUsers: ["app", "blocked-users"] as const,
  searchHistory: ["app", "search-history"] as const,
};
